### ISSUE TITLE
用重新pack后的文件重新打包app，覆盖安装之前的app，出现闪退。

### ISSUE THREAD

**Issue by lyloou** [bmfe/WeexErosFramework#26]
用重新pack后的文件重新打包app，覆盖安装之前的app，出现闪退。
在网上找了许久，还没找到解决方案。

```
07-10 20:04:26.839 12074-12550/com.renrenyoupin.activity.debug I/bspatch.c: Point 9
    Point 10
    理论上此处就成功了
07-10 20:04:27.388 12074-12074/com.renrenyoupin.activity.debug W/System.err: java.util.zip.ZipException: End Of Central Directory signature not found
        at java.util.zip.ZipFile.readCentralDir(ZipFile.java:415)
        at java.util.zip.ZipFile.<init>(ZipFile.java:175)
        at java.util.zip.ZipFile.<init>(ZipFile.java:131)
        at com.benmu.framework.manager.impl.FileManager.extractZip(FileManager.java:182)
        at com.benmu.framework.update.VersionChecker.checkZipValidate(VersionChecker.java:209)
        at com.benmu.framework.update.VersionChecker.access$400(VersionChecker.java:35)
        at com.benmu.framework.update.VersionChecker$4.onSuccess(VersionChecker.java:258)
```

**Comment by lyloou** [comment]
想到了一个解决办法：
即，在`下载patch md5校验出错`的时候去下载全量包
```
L.e("version", "下载patch md5校验出错");
//删除生成的新包和patch包
FileManager.deleteFile(new File(FileManager.getTempBundleDir
        (mContext), FileManager.PATCH_NAME));
FileManager.deleteFile(new File(FileManager.getTempBundleDir
        (mContext), FileManager.TEMP_BUNDLE_NAME));
newVersion = null;
mCurrentStatus = Constant.Version.SLEEP;
downloadCompleteZip(); // 校验失败的时候，去下载全量包
```
